server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27018
      database: catalog
      username: usr-catalog
      password: pwd-catalog


queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue
