server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3366/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  movie:
    name: MovieQueue