server:
  port: ${PORT:${SERVER_PORT:0}}

queue:
  serie:
    name: SerieQueue
    
spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: serie
      username: usr-serie
      password: pwd-serie

