server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: serie
      username: usr-serie
      password: pwd-serie

queue:
  serie:
    name: SerieQueue